name: shimmer
description: A package provides an easy way to add shimmer effect in Flutter project
version: 1.1.0
author: Hung Duy Ha <hunghd.yb@gmail.com>
contributors: Gregor Weber <The-Redhat>
homepage: https://github.com/hnvn/flutter_shimmer
environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: